name: First-Sample-Workflow
on: [push]
jobs: 
  workflow-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: echo "The ${{ github.repository }} has been cloned to the runner."
      - run: ls $ {{ github.workspace }}